import Nav from '@/components/Nav';
import './globals.css';
import { Space_Grotesk } from 'next/font/google';
import Footer from '@/components/Footer';

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={spaceGrotesk.className}>
        <Nav />
        <main className='relative min-h-[20vh] py-4 sm:py-6 xl:py-12'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
